import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/Components/Navbar";
import Providers from "@/redux/Providers";

const inter = Inter({ subsets: ["latin"] });
const css = 'h-full bg-blue-900'

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Providers>
      <body className={`${inter.className},${css}`}>
        {children}
        </body>
      </Providers> 
    </html>
  );
}
